HOST_PROTOCOL = "http"
HOST_NAME = "10.0.10.4"
HOST_PORT = "1880"

TARGET_PATH="timbre"
MSG_PAYLOAD="Son%C3%B3%20el%20timbre"
MSG_TITLE="%C2%A1Timbre!"
MSG_SUBJECT="tema"

LED_PIN="LED"
DOORBELL_PIN=10

SERIAL_LOGS=False

